"use client";

import { useState } from "react";
import Link from "next/link";
import { FileText, Download, Trash2, Plus, Search, FilePlus, X } from "lucide-react";

import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Modal } from "@/components/ui/Modal";
import { Card } from "@/components/ui/Card";
import { cn } from "@/lib/utils";
import { deleteDocument } from "./actions";
import type { GeneratedDocument } from "@/lib/types";

type ModalState = { type: "delete"; doc_id: string } | { type: "preview"; doc_id: string } | null;

type DocumentsContentProps = {
  orgSlug: string;
  docs: GeneratedDocument[];
  docTypes: Array<{ id: string; name: string; key: string }>;
  canCreate: boolean;
  canDelete: boolean;
  baseUrl: string;
  search: string;
  document_type_id: string;
  date_from: string;
  date_to: string;
  error: string;
  success: string;
};

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function DocumentsContent({
  orgSlug, docs, docTypes, canCreate, canDelete, baseUrl,
  search, document_type_id, date_from, date_to, error, success,
}: DocumentsContentProps) {
  const [modal, setModal] = useState<ModalState>(null);

  const selectedDoc = docs.find((d) => d.id === modal?.doc_id);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-main">Documents</h1>
          <p className="text-sm text-muted mt-1">Manage generated documents</p>
        </div>
        <div className="flex gap-2">
          <Link href={`${baseUrl}/templates`}>
            <Button variant="outline" size="sm">
              <FileText className="h-4 w-4 mr-1.5" />
              Templates
            </Button>
          </Link>
          {canCreate && (
            <Link href={`${baseUrl}/generate`}>
              <Button size="sm">
                <Plus className="h-4 w-4 mr-1.5" />
                Generate
              </Button>
            </Link>
          )}
        </div>
      </div>

      {(error || success) && (
        <div className={cn("rounded-xl border px-4 py-3 text-sm", error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700")}>
          {error || success}
        </div>
      )}

      <Card>
        <form action={baseUrl} method="GET" className="flex flex-wrap gap-3 p-4 border-b border-soft">
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted" />
            <input
              name="search"
              defaultValue={search ?? ""}
              placeholder="Search by title or employee..."
              className="w-full rounded-xl border border-soft bg-white pl-9 pr-4 py-2.5 text-sm focus:ring-2 focus:ring-violet-500"
            />
          </div>
          <select
            name="document_type_id"
            defaultValue={document_type_id ?? ""}
            className="rounded-xl border border-soft bg-white px-3 py-2.5 text-sm focus:ring-2 focus:ring-violet-500"
          >
            <option value="">All Types</option>
            {docTypes.map((t) => (
              <option key={t.id} value={t.id}>{t.name}</option>
            ))}
          </select>
          <input
            name="date_from"
            type="date"
            defaultValue={date_from ?? ""}
            className="rounded-xl border border-soft bg-white px-3 py-2.5 text-sm focus:ring-2 focus:ring-violet-500"
          />
          <input
            name="date_to"
            type="date"
            defaultValue={date_to ?? ""}
            className="rounded-xl border border-soft bg-white px-3 py-2.5 text-sm focus:ring-2 focus:ring-violet-500"
          />
          <Button type="submit" size="sm" variant="secondary">Filter</Button>
        </form>

        {docs.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-soft text-left text-xs font-bold uppercase tracking-wider text-muted">
                  <th className="px-4 py-3">Title</th>
                  <th className="px-4 py-3">Employee</th>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Generated By</th>
                  <th className="px-4 py-3">Generated At</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {docs.map((doc) => (
                  <tr key={doc.id} className="border-b border-soft hover:bg-slate-50 transition-colors">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <FileText className="h-4 w-4 text-violet-500 shrink-0" />
                        <span className="text-sm font-medium text-main">{doc.title}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-sm">{doc.employee?.full_name || doc.employee?.email || "—"}</td>
                    <td className="px-4 py-3">
                      <Badge variant="secondary">{doc.document_type?.name || "—"}</Badge>
                    </td>
                    <td className="px-4 py-3 text-sm">{doc.generated_by_user?.full_name || doc.generated_by_user?.email || "—"}</td>
                    <td className="px-4 py-3 text-sm text-muted">{formatDate(doc.generated_at)}</td>
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-1">
                        <Button variant="ghost" size="sm" className="h-8 w-8 p-0 rounded-xl" onClick={() => setModal({ type: "preview", doc_id: doc.id })}>
                          <FileText className="h-3.5 w-3.5" />
                        </Button>
                        <a href={`/api/documents/${orgSlug}/${doc.id}/pdf`}>
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0 rounded-xl hover:text-violet-600">
                            <Download className="h-3.5 w-3.5" />
                          </Button>
                        </a>
                        {canDelete && (
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0 rounded-xl hover:bg-red-50 hover:text-red-600" onClick={() => setModal({ type: "delete", doc_id: doc.id })}>
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="flex flex-col items-center py-12 text-center text-muted">
            <FilePlus className="h-10 w-10 mb-3 text-slate-300" />
            <p className="text-lg font-medium">No documents found</p>
            <p className="text-sm mt-1 mb-4">
              {search || document_type_id ? "Try different filters." : "Start by generating a new document."}
            </p>
            {canCreate && !search && !document_type_id && (
              <Link href={`${baseUrl}/generate`}>
                <Button variant="outline">Generate your first document</Button>
              </Link>
            )}
          </div>
        )}
      </Card>

      {selectedDoc && modal?.type === "delete" && (
        <Modal isOpen={true} onClose={() => setModal(null)} title="Delete Document" size="sm">
          <div className="space-y-6 text-center py-4">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-red-50 text-red-600 border border-red-100 shadow-inner">
              <Trash2 className="h-8 w-8" />
            </div>
            <div>
              <h4 className="text-xl font-bold text-main tracking-tight">Delete Document?</h4>
              <p className="mt-2 text-xs text-muted">Delete &quot;{selectedDoc.title}&quot;?</p>
            </div>
            <form action={deleteDocument} className="flex flex-col gap-2 px-2">
              <input type="hidden" name="organization_slug" value={orgSlug} />
              <input type="hidden" name="doc_id" value={selectedDoc.id} />
              <Button variant="danger" type="submit" className="py-3">Delete</Button>
              <Button variant="outline" className="w-full py-3 border-none text-muted" onClick={() => setModal(null)}>Cancel</Button>
            </form>
          </div>
        </Modal>
      )}

      {selectedDoc && modal?.type === "preview" && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setModal(null)} />
          <div className="relative w-full max-w-[95vw] h-[90vh] overflow-hidden rounded-2xl bg-white shadow-2xl flex flex-col">
            <div className="flex items-center justify-between border-b border-soft px-6 py-4 shrink-0">
              <div>
                <h3 className="text-lg font-semibold text-main tracking-tight">{selectedDoc.title}</h3>
                <p className="text-xs text-muted mt-0.5">
                  Generated by {selectedDoc.generated_by_user?.full_name || selectedDoc.generated_by_user?.email || "Unknown"} on {formatDate(selectedDoc.generated_at)}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <a href={`/api/documents/${orgSlug}/${selectedDoc.id}/pdf`}>
                  <Button size="sm">
                    <Download className="h-4 w-4 mr-1.5" />
                    Download PDF
                  </Button>
                </a>
                <button onClick={() => setModal(null)} className="rounded-lg p-1 text-muted hover:bg-slate-100 transition-colors">
                  <X className="h-5 w-5" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto bg-white">
              <iframe
                src={`/api/documents/${orgSlug}/${selectedDoc.id}/preview`}
                className="w-full h-full border-0"
                title="Document Preview"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
